import { en } from "@/i18n/messages/en";
import type { MessageShape } from "@/i18n/types";

export const zhCN = {
  common: {
    actions: { add: "添加", back: "返回", cancel: "取消", clear: "清除", close: "关闭", create: "创建", delete: "删除", edit: "编辑", refresh: "刷新", reset: "重置", retry: "重试", save: "保存", search: "搜索", upload: "上传" },
    states: { cancelled: "已取消", checking: "检查中", completed: "已完成", connected: "已连接", disabled: "已禁用", enabled: "已启用", error: "错误", fail: "失败", failed: "失败", idle: "空闲", needsKey: "需要密钥", offline: "离线", pass: "通过", pending: "等待中", processing: "处理中", queued: "排队中", ready: "就绪", running: "运行中", succeeded: "成功" },
    loading: { content: "正在加载内容", documents: "正在加载文档", memory: "正在加载持久记忆" },
    errors: { title: "发生了错误", dismiss: "关闭错误提示", notificationDismiss: "关闭通知", generic: "发生了错误，请稍后重试。" },
    values: { never: "从未", none: "无", notAvailable: "不适用", unknown: "未知" },
    relativeTime: { justNow: "刚刚", minutesAgo: "{count} 分钟前", hoursAgo: "{count} 小时前" },
    counts: { documentsOne: "{count} 个文档", documentsOther: "{count} 个文档", events: "{count} 个事件", graders: "{count} 个评分器", basesOne: "已绑定 {count} 个知识库", basesOther: "已绑定 {count} 个知识库", retrievedChunksOne: "检索到 {count} 个引用片段", retrievedChunksOther: "检索到 {count} 个引用片段" },
  },
  language: { label: "切换语言", english: "English", chinese: "简体中文" },
  navigation: {
    skip: "跳到主要内容", primary: "主导航", workspace: "工作区", dashboard: "仪表盘", agents: "智能体", builder: "智能体构建器", playground: "调试台", evaluations: "评测", runDetail: "运行详情",
    dashboardTitle: "工作区概览", agentsTitle: "智能体定义", builderTitle: "配置智能体", playgroundTitle: "测试与检查", evaluationsTitle: "回归评测", runTitle: "执行详情", dashboardAria: "Agent Studio 仪表盘", runDisabled: "运行智能体后可查看详情", developerWorkspace: "开发者工作区", localWorkspace: "本地工作区", checkingApi: "正在检查 API", apiConnected: "已连接", apiOffline: "API 离线", profile: "工作区资料",
  },
  dashboard: {
    eyebrow: "概览", title: "仪表盘", description: "查看 Agent Studio 已持久化的真实运行和实测指标。", createAgent: "创建智能体", metricsLabel: "工作区指标",
    metrics: { agents: "智能体", agentsSaved: "已保存的定义", agentsEmpty: "创建第一个智能体", totalRuns: "运行总数", totalRunsMeta: "后端持久化运行", successRate: "成功率", successMeta: "{completed} 个已完成 · {failed} 个失败", successEmpty: "暂无完成或失败的运行", averageDuration: "平均耗时", averageAwaiting: "等待近期终态运行", averageRecent: "最近 30 次运行", cancelled: "已取消", cancelledMeta: "与失败分开统计", cancelledAwaiting: "等待遥测数据" },
    recent: { title: "最近运行", description: "从后端持久化存储加载的真实执行。", latest: "查看最新运行", emptyTitle: "暂无运行记录", emptyDescription: "在调试台执行智能体后，指标和追踪链接会显示在这里。", openPlayground: "打开调试台", buildAgent: "构建智能体", run: "运行", agent: "智能体", status: "状态", toolCalls: "工具调用", duration: "耗时", started: "开始时间", action: "操作", inspect: "查看运行 {id}" },
  },
  agents: {
    eyebrow: "定义", title: "智能体", description: "连接到真实 Agent Studio Runtime 的版本化配置。", new: "新建智能体", listLabel: "智能体定义", emptyTitle: "暂无智能体定义", emptyDescription: "创建包含提示词和至少一个已启用工具的定义，即可使用调试台。", openBuilder: "打开智能体构建器", tools: "工具", knowledgeBase: "知识库", knowledgeNotBound: "未绑定", memory: "记忆", lastRun: "上次运行", deterministicMock: "确定性 Mock", providerModel: "Provider 模型", openPlayground: "在调试台中打开", unknown: "未知智能体",
  },
  builder: {
    eyebrow: "定义编辑器", title: "智能体构建器", description: "配置运行行为，并在保存前预览持久化定义。", identity: "身份与行为", identityHelp: "由 Agent Studio API 持久化的核心字段。", name: "名称", nameHelp: "便于在运行和追踪中识别的名称。", prompt: "提示词", promptHelp: "所选 Runtime 使用的指令。", required: "名称和提示词为必填项。", modelRequired: "请输入 {provider} 模式的 Provider 模型 ID。", runtime: "Runtime", runtimeHelp: "选择确定性测试路径，或使用已配置的 Provider。", runtimeMode: "Runtime 模式", noApiKey: "无需 API 密钥", model: "模型", mockHelp: "Mock Runtime 是确定性的，不会调用模型。", configuredHelp: "已配置 {provider} 密钥。运行时请使用准确的模型 ID。", unconfiguredHelp: "尚未配置 {provider} 密钥。可以保存定义，但运行会被阻止。", deterministicMock: "确定性 Mock", modelPlaceholder: "输入 Provider 模型 ID", capabilities: "能力", capabilitiesHelp: "只能启用当前后端契约已支持的能力。", calculator: "计算器", calculatorHelp: "安全的算术表达式", enableCalculator: "启用计算器", knowledge: "知识库", knowledgeHelp: "绑定真实知识库以启用 knowledge_search", noKnowledge: "暂无可用知识库", noKnowledgeHelp: "请先在下方知识库 / RAG 区域创建并处理文档，再在这里绑定。", durableMemory: "持久记忆", durableMemoryHelp: "跨成功运行检索并保存智能体范围内的事实", enableMemory: "启用持久记忆", limits: "限制", limitsHelp: "当前 Agent API 不提供可编辑的 Runtime 限制。", maxIterations: "最大迭代次数", timeout: "超时", engineDefault: "引擎默认值", saving: "正在保存定义…", saveAgent: "保存智能体", previewAria: "智能体实时预览", livePreview: "实时预览", unsaved: "未保存的定义", definition: "智能体定义", untitled: "未命名智能体", promptPlaceholder: "智能体提示词会显示在这里。", tools: "工具", noTools: "无工具", notBound: "未绑定", modelNotSet: "未设置模型", runAfterSaving: "保存后运行", previewOnly: "仅供预览", previewNote: "保存后会创建真实的后端定义。不支持的能力仍保持禁用。",
  },
  playground: {
    eyebrow: "执行工作区", title: "调试台", description: "运行真实智能体，并检查流式传输的标准化追踪事件。", activeAgent: "当前智能体", emptyTitle: "请选择智能体", emptyDescription: "调试台需要已保存的定义才能执行运行。", build: "构建智能体", deterministicRuntime: "确定性 Mock Runtime", openAiRuntime: "OpenAI Runtime", cancelRun: "取消运行", ready: "可以开始测试 {name}", readyHelp: "发送消息以启动真实运行。Runtime 发出事件时，追踪面板会同步更新。", suggestionOne: "计算 128 × 37 + 456", suggestionTwo: "尝试另一个表达式", you: "你", working: "正在通过 {runtime} Runtime 处理…", persistedOutput: "来自已持久化的 Agent Studio 运行", failedTitle: "运行失败", failedHelp: "Runtime 未能完成此请求。", cancelledTitle: "运行已取消", cancelledHelp: "运行在完成前被取消，已持久化的追踪仍可查看。", message: "消息", placeholder: "让智能体计算一些内容…", shortcut: "⌘ Enter 运行", starting: "正在启动运行…", runAgent: "运行智能体", tracePanel: "实时追踪面板", liveTrace: "实时追踪", waiting: "等待运行", runDetail: "运行详情", clearTitle: "清除此对话？", clearDescription: "这会从调试台移除当前对话。已持久化的运行仍可在最近运行中查看。", clearConfirm: "清除对话",
  },
  trace: {
    filtersLabel: "追踪筛选器", liveAria: "实时运行追踪", emptyTitle: "追踪会显示在这里", emptyDescription: "每个模型步骤和工具调用都会按执行顺序流式显示。", noMatch: "没有符合此筛选条件的事件。", all: "全部", lifecycle: "生命周期", runtime: "Runtime / LLM", tools: "工具", knowledge: "知识库 / RAG", memory: "记忆", errors: "错误", event: "事件", system: "系统", model: "模型", routing: "路由", tool: "工具", runtimeCategory: "Runtime", error: "错误", output: "输出", runStarted: "运行已开始", stepStarted: "步骤已开始", llmRequest: "LLM 请求", llmRetry: "LLM 重试", llmResponse: "LLM 响应", toolSelected: "已选择工具", toolCall: "工具调用", toolResult: "工具结果", toolFailed: "工具失败", stepCompleted: "步骤已完成", memoryRetrieved: "已检索记忆", memorySkipped: "已跳过记忆检索", memoryWritten: "已写入记忆", finalAnswer: "最终答案", runFailed: "运行失败", runCancelled: "运行已取消", eventRecorded: "事件已记录", calculator: "计算器", knowledgeTool: "知识库", citations: "知识库引用来源", source: "来源", document: "文档", chunk: "片段", metadata: "元数据", score: "得分", step: "步骤", call: "调用",
  },
  runs: {
    eyebrow: "追踪浏览器", title: "运行详情", descriptionEmpty: "运行在调试台启动后，可在这里检查执行过程。", noRunTitle: "未选择运行", noRunDescription: "请执行智能体，或从仪表盘选择最近运行。", openPlayground: "打开调试台", description: "正在检查 {name} 的运行 {id}。", backEvaluations: "返回评测", backPlayground: "返回调试台", runAgain: "再次运行", metrics: "可观测性指标", runId: "运行 ID（Run ID）", duration: "耗时", steps: "步骤", events: "事件", toolCalls: "工具调用", toolFailures: "工具失败", providerRequests: "Provider 请求", inputTokens: "输入 Token", outputTokens: "输出 Token", totalTokens: "Token 总数", timeline: "执行时间线", timelineDescription: "按持久化顺序显示应用自有事件。", timelineAria: "运行执行时间线", userInput: "用户输入", input: "输入", unknownEvent: "未知事件", failed: "失败", final: "最终结果", modelRequest: "模型请求", modelRetry: "模型重试", modelResponse: "模型响应", runStartedEvent: "运行已开始", stepStartedEvent: "步骤已开始", llmEvent: "LLM", llmRetryEvent: "LLM 重试", toolSelectedEvent: "已选择工具", toolCallEvent: "工具调用", toolResultEvent: "工具结果", stepCompletedEvent: "步骤已完成", memoryRetrievedEvent: "已检索记忆", memorySkippedEvent: "已跳过记忆检索", memoryWrittenEvent: "已写入记忆", runCancelledEvent: "运行已取消", metadataTitle: "运行元数据", status: "状态", runtime: "Runtime", provider: "Provider", apiStyle: "API 风格", model: "模型", termination: "终止原因", started: "开始时间", completed: "完成时间", finalOutput: "最终输出", error: "错误",
    terminationReasons: { maxSteps: "已达到最大步骤数", timeout: "已超时", cancelled: "已取消", toolError: "工具错误", providerError: "Provider 错误", completed: "已完成", failed: "失败" },
  },
  knowledge: {
    eyebrow: "知识库 / RAG", title: "让智能体基于可检查的来源作答。", description: "创建集合，异步处理真实文档，并检查排序后的片段。", baseName: "知识库名称", basePlaceholder: "产品手册", descriptionLabel: "描述", descriptionPlaceholder: "政策和操作说明", working: "处理中…", collections: "集合", emptyCollections: "创建一个知识库以开始。", documents: "文档", chooseFile: "选择 txt、md 或 pdf", uploadIngest: "上传并处理", noDocuments: "尚未上传文档。", testRetrieval: "测试检索", queryPlaceholder: "询问与这些来源有关的问题", searching: "正在搜索…", hybridSearch: "语义 + 关键词搜索", noMatches: "未找到匹配的片段。", score: "得分", source: "来源", chunk: "片段", page: "页码", loadFailed: "无法加载文档。", createFailed: "无法创建知识库。", uploadFailed: "无法上传文档。", ingestionFailed: "文档处理失败。", ingestionRunning: "文档仍在处理中，请刷新以查看状态。", searchFailed: "搜索失败。",
  },
  memory: {
    eyebrow: "长期记忆", title: "已记住的事实", updating: "更新中…", on: "开启", off: "关闭", disabledNote: "记忆已关闭。运行不会检索或写入事实。", empty: "此智能体尚未保存持久事实。", factMeta: "重要性 {importance} · 过期时间 {expires}", deleteAria: "删除记忆：{content}",
  },
  evaluation: {
    eyebrow: "质量", title: "评测", description: "智能体行为是否符合预期？使用真实的持久化运行执行确定性回归评测。", createSuite: "创建评测套件", emptyTitle: "暂无评测套件", emptyDescription: "创建套件以评测最终答案、工具选择、RAG、记忆、步骤和延迟。", builderEyebrow: "评测", createTitle: "创建评测套件", editTitle: "编辑评测套件", builderDescription: "为真实 Agent Studio 执行定义确定性预期。", suiteName: "套件名称", suitePlaceholder: "计算器回归测试", agent: "智能体", selectAgent: "选择智能体", descriptionLabel: "描述", descriptionPlaceholder: "此套件要保护的行为", cases: "用例", casesDescription: "每个用例都会启动一个隔离的真实智能体运行。", addCase: "添加用例", case: "用例 {count}", untitledCase: "未命名用例", deleteCase: "删除用例 {count}", caseName: "用例名称", enabled: "已启用", input: "输入", memorySeed: "评测专用记忆种子", optionalIsolated: "可选；每个用例相互隔离", memoryPlaceholder: "项目代号是 Aurora", graders: "评分器", addGrader: "添加评分器", graderType: "评分器 {count} 类型", required: "必需", deleteGrader: "删除评分器 {count}", saving: "正在保存…", saveSuite: "保存套件", suiteEyebrow: "评测套件", suiteDescription: "通过真实智能体 Runtime 执行的确定性预期。", allSuites: "所有套件", starting: "正在启动…", runEvaluation: "运行评测", revision: "修订版本", deleteSuite: "删除套件", deleteConfirm: "删除 {name}？历史评测运行仍可通过直接链接访问。", casesSnapshot: "运行开始时会生成定义快照。", caseMetaWithMemory: "{count} 个评分器 · 隔离的记忆设置", caseMetaNoSetup: "{count} 个评分器 · 无设置", runEyebrow: "评测运行", runTitle: "运行 {id}", runDescription: "套件修订版本 {revision} · 确定性离线评分器", retryRefresh: "重试刷新", progress: "进度", pass: "通过", fail: "失败", error: "错误", passRate: "通过率", average: "平均值", summaryAria: "评测摘要", caseResults: "用例结果", linkedRuns: "{count} 个真实智能体运行已关联到持久化追踪。", filtersAria: "用例结果筛选器", noFilterMatches: "没有符合此筛选条件的用例。", selectCase: "选择用例", selectCaseDescription: "选择结果以检查实际输出和评分证据。", viewRunTrace: "查看运行追踪", actualOutput: "实际最终输出", runStatus: "运行状态", graderResults: "评分结果", expected: "预期", actual: "实际", evidence: "证据", noEvidence: "无", suite: "套件", lastStatus: "上次状态", updated: "更新时间", openSuite: "打开 {name}", revisionFallback: "修订版本 {revision}", expectedText: "预期文本", caseSensitive: "区分大小写", toolName: "工具名称", expectedSource: "预期来源", sourcePlaceholder: "upload://source.md（可选）", maximumSteps: "最大步骤数", maximumDuration: "最大耗时（ms）", expectedRunStatus: "预期运行状态", noConfiguration: "无需配置", loadFailed: "无法加载评测套件。", refreshFailed: "无法刷新评测运行。", suiteLoadFailed: "无法加载评测套件。", saveFailed: "无法保存评测套件。", deleteFailed: "无法删除评测套件。", runLoadFailed: "无法加载评测运行。", runStartFailed: "无法启动评测运行。", cancelFailed: "无法取消评测。", caseFallback: "评测用例",
    graderTypes: { runStatus: "运行状态", finalOutput: "最终输出非空", exactMatch: "完全匹配", contains: "包含", toolSelected: "已选择工具", toolNotSelected: "未选择工具", retrievalHit: "检索命中", citation: "引用来源", memoryRetrieved: "已检索记忆", maxSteps: "最大步骤数", maxDuration: "最大耗时" },
  },
  notifications: {
    runCompletedTitle: "运行已完成", runCompletedMessage: "已持久化 {count} 个追踪事件。", runFailedTitle: "运行失败", runFailedMessage: "Runtime 返回了错误。", runCancelledTitle: "运行已取消", runCancelledMessage: "已持久化的追踪仍可查看。", agentSavedTitle: "智能体已保存", agentSavedMessage: "{name} 已可在调试台中使用。", saveFailedTitle: "保存失败", memoryEnabledTitle: "记忆已启用", memoryDisabledTitle: "记忆已禁用", memoryEnabledMessage: "后续运行可以检索和写入持久事实。", memoryDisabledMessage: "后续运行不会检索或写入持久事实。", memoryDeletedTitle: "记忆已删除", memoryDeletedMessage: "已从此智能体移除该持久事实。", runStartFailedTitle: "无法启动运行", cancellationTitle: "已请求取消", cancellationMessage: "Runtime 将持久化一个已取消终态事件。", clearedTitle: "对话已清除", clearedMessage: "已持久化的运行仍可从仪表盘查看。",
  },
  studioErrors: {
    memoryLoad: "无法加载持久记忆。", malformedEvent: "已忽略格式错误的追踪事件。请刷新运行以加载持久化事件。", refreshRun: "无法刷新运行状态。", streamInterrupted: "实时追踪连接已中断。已接收的事件会保留；请在 API 可用时重试。", recoverRun: "无法恢复运行状态。", agentsLoad: "无法加载智能体定义。", knowledgeLoad: "无法加载知识库。", requestedRun: "无法加载请求的运行。", selectedRun: "无法加载所选运行。", saveAgent: "无法保存智能体定义。", memoryUpdate: "无法更新记忆设置。", memoryDelete: "无法删除该持久事实。", runStart: "无法启动智能体运行。", runCancel: "无法取消运行。",
  },
} satisfies MessageShape<typeof en>;
